name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*.*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: windows-latest, outfile: executable_windows.exe }
          - { os: macos-latest, outfile: executable_macOS }
          - { os: ubuntu-latest, outfile: executable_linux }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: g++ ./src/main.cpp -o ${{ matrix.config.outfile }}

      - name: Run
        run: ./${{ matrix.config.outfile }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.config.outfile }}
